### DISCUSSION TITLE
Static Table Widget: Keep Header Row At Top

### DISCUSSION THREAD

**Discussion by juftin** [Textualize/textual#1556] [Q&A] [answered]
Is there a way to keep a `rich.Table`'s Header Row frozen at the top of a `Static` widget? Ideally I'd like to do something like this in CSS:
```css
#header {
    position: sticky;
}
```
