### DISCUSSION TITLE
Screens supporting CSS and/or CSS_PATH

### DISCUSSION THREAD

**Discussion by lllama** [Textualize/textual#1663] [Ideas]
I associate Screens as almost separate Apps (at least in terms of display) and it is often necessary to give a Screen's widgets some style tweaks. It would be nice to give them their own CSS styles. I suppose I still want the base styles to apply so the selectors would need to be tweaked behind the scenes. E.g. 
```css
Static {
    border: solid red;
}
```
Would become:

```css
MyScreen Static {
    border: solid red;
}
```
