### DISCUSSION TITLE
Ignoring CSS Lint Errors on CSS Variables

### DISCUSSION THREAD

**Discussion by bphunter1972** [Textualize/textual#2169] [Q&A] [answered]
I'm using VSCode. Has anyone figured out how to ignore the errors in css for the textual variables, like the following?

```css
.buttons {
    height: 5;
    border: $success-lighten-3 solid;
           ^^^
}
```
