### DISCUSSION TITLE
Any way to implement responsive layout? (like wrap)

### DISCUSSION THREAD

**Discussion by laixintao** [Textualize/textual#3250] [Q&A] [answered]
Hi,

I want to list 4 items in Horizontal:

```
A B C D
```

When the parent width is small, I do not want it to scroll, is there a way to make it `wrap`?
```
A B C
D
```

Or even better:

```
A B
C D
```

**Comment by davep** [comment, marked as answer]
Currently we don't have a `layout` option that works that way, although it's something we'd like to add.

**Reply by laixintao** [reply]
Nice! Thanks! @davep 



thank you so much! you are a good man ❤️

**Reply by laixintao** [reply]
(moved my another questions to https://github.com/Textualize/textual/discussions/3251)

**Comment by TomJGooding** [comment]
The [grid layout](https://textual.textualize.io/guide/layout/#grid) I think might get you close?

> We can tell Textual to add new rows on demand to fit the number of widgets, by omitting the number of rows from grid-size. The following example creates a grid with three columns, with rows created on demand [...] Since we specified that our grid has three columns (grid-size: 3), and we've yielded seven widgets in total, a third row has been created to accommodate the seventh widget.

**Reply by laixintao** [reply]
Thanks, I have read that, but that's not what I want.

By that way, I always have 3 cols, and new items get auto layouted to either new row, or last row(if have space).

But what I want is that, when the space is small, I want the layout display as 2 cols per row or even 1 col,

if the screen is big, I want to have more cols in same row, for e.g. 5 cols.

like a responsive webpage.

**Reply by davep** [reply]
I think the issue here though is that if the terminal is wide (for hand-waved values of wide) the wish is to have all four elements on the same row, but if the terminal is narrow (for hand-waved values or narrow), the wish is to have the first 3 on the first row and the 4th wrap to a second row.

With grid you're always going to get the same number of elements on the row, right?

Edit to add: or what @laixintao said ;-)

**Reply by TomJGooding** [reply]
Ah gotcha, sorry for the confusion!

**Reply by willmcgugan** [reply]
We are planning on a "inline" layout that works like this. In the meantime, you could handle the Resize event and calculate the number of columns based on that.

**Reply by laixintao** [reply]
Nice thanks @willmcgugan , I will do that

**Comment by ihorh** [comment]
If this discussion is still relevant I seem to have found a nice CSS-ish way to do sort of responsive design which feels very natural:

1. I hardcode width breakpoint values and corresponding TCSS classes: like this:
```python
    WIDTH_BREAKPOINS = {
        64: "breakpoint-sm",
        128: "breakpoint-md",
        192: "breakpoint-lg",
```
2. In parent widget which need to be "responsive, I define `on_resize` like this:
```python
    def on_resize(self, event: Resize):
        print("resize:", event)
        _ = [self.query().remove_class(cls) for cls in self.WIDTH_BREAKPOINS.values()]
        keys = sorted(self.WIDTH_BREAKPOINS.keys(), reverse=True)
        for k in keys:
            if event.size.width > k:
                self.query().add_class(self.WIDTH_BREAKPOINS[k])
                break
```
basically here I set breakpoint related class based on width
3. In TCSS I can do crazy stuff like this and it works like expected:
```css
Grid {
    width: 100%;
    height: 1fr;
    # height: auto;
    # max-width: 200;
    grid-size: 3;
    border: solid red;
    grid-gutter: 0;

    &.breakpoint-sm { grid-size: 1; }
    &.breakpoint-md { grid-size: 2; }
    &.breakpoint-lg { grid-size: 3; }
    .box-hdr {
        height: 100%;
        border: solid green;
        width: auto;
        min-width: 48;
        max-width: 200;

        &.breakpoint-sm { column-span: 1; row-span:1 }
        &.breakpoint-md { column-span: 1; row-span:20 }
        &.breakpoint-lg { column-span: 3; row-span:1 }
    }
}
```

What id does for different screen sizes:
* large screen: header on top and child widgets arranged in 3 columns
* medium screen: "header" on the left, and child widgets put into one column on the right
* small screen: everything arranged in one column with header being int the first row

Sorry, I just prototyped it and code is not most effective, I can refine it later and post full working example if anyone is interested.

Also maybe someone here is more experienced than me (I'm very inexperienced :-) ) and can suggest improvements or develop this concept even further.


Update: Layout is pretty straightforward, I forgot to post it initially:

```python
def compose(self) -> ComposeResult:
        with Horizontal():
            with Grid():
                yield Static("header content, " * 20, id="hdr", classes="box-hdr")
                yield Static("123456789_" * 8, classes="box")
                yield Static("Two", classes="box")
                yield Static("Three", classes="box")
                yield Static("Four", classes="box")
                yield Static("Five", classes="box")
                yield Static("Six", classes="box")
```
