### DISCUSSION TITLE
RadioSet horizontal stacking of Radiobuttons

### DISCUSSION THREAD

**Discussion by JoeZiminski** [Textualize/textual#3597] [Q&A] [answered]
Apologies if I have missed this in the documentation somewhere, is it possible to stack the radiobuttons within a [RadioSet](https://textual.textualize.io/widgets/radioset/) horizontally?

**Comment by davep** [comment, marked as answer]
You should find that you can use normal CSS to do that; for example:

```scss
    RadioSet {
        layout: horizontal;
    }
```
