### DISCUSSION TITLE
Markdown toggle focus between can_focus_children and normal mode

### DISCUSSION THREAD

**Discussion by villekr** [Textualize/textual#4227] [Q&A] [answered]
I'm looking for a preferred way to implement focus travelsal in Markdown widget so that:
- "focus mode" can be toggled between markdown itself and it's children
  - when hitting "enter" focus mode is "children". By pressing "tab" focus cycles between markdown widget's children (and not out of this selected markdown widget)
  - when hitting "escape" normal focus mode is restored. By pressing "tab" focus cycles between markdown widget and any other focusable widgets

In my code below I accomplished kind of the desired behaviour, but there are two questions:
- Is there a more simpler way to achieve this?
- How to prevent focus jumping out of markdown's children when focus mode is "children" 

markdown.py
```python
from textual.app import App, ComposeResult
from textual.widgets import Markdown
from textual.containers import Horizontal
from textual import events

EXAMPLE_MARKDOWN = """\
# Markdown Document

This is an example of Textual's `Markdown` widget.

## Features

Markdown syntax and extensions are supported.

- Typography *emphasis*, **strong**, `inline code` etc.
- Headers
- Lists (bullet and ordered)
- Syntax highlighted code blocks
- Tables!
"""


class MyMarkdown(Markdown):
    can_focus = True

    def on_key(self, event: events.Key) -> None:
        if event.key == "enter":
            # Enable "children" focus mode
            self.can_focus_children = True
            for child in self.children:
                child.can_focus = True
            self.children[0].focus()
        elif event.key == "escape":
            # Restore "normal" focus mode
            self.can_focus_children = False
            for child in self.children:
                child.can_focus = False
            self.focus()


class MarkdownExampleApp(App):
    CSS_PATH = "markdown.tcss"

    def compose(self) -> ComposeResult:
        with Horizontal():
            yield MyMarkdown(EXAMPLE_MARKDOWN)
            yield MyMarkdown(EXAMPLE_MARKDOWN)


if __name__ == "__main__":
    app = MarkdownExampleApp()
    app.run()
```

markdown.tcss
```css
Markdown {
    width: 50%;
    margin: 1 1 1 1;
}

Markdown:focus {
    background: $accent;
}

MarkdownH1:focus {
    background: $accent;
}

MarkdownParagraph:focus {
    background: $accent;
}

MarkdownH2:focus {
    background: $accent;
}

MarkdownBulletList:focus {
    background: $accent;
}
```
