### DISCUSSION TITLE
What is the best way to play audio AFTER a screen is mounted?

### DISCUSSION THREAD

**Discussion by jessebot** [Textualize/textual#4419] [Q&A] [answered]
Hi Textual friends and community!

Currently, if I use the playsound library to play audio on mount, it plays the audio before displaying any widgets on the screen. Is there a better event to wait for all widgets to be displayed before playing a sound?

Here's a brief example of my troubles:

<details>
<summary>pyproject.toml deps</summary>

```toml
[tool.poetry.dependencies]
python        = ">=3.11,<4.0"
textual       = "^0.56"
playsound     = {git = "https://github.com/taconi/playsound"}
pyfiglet      = "^1.0"
```
</details>

```python
from playsound import playsound
from pyfiglet import Figlet
from textual.app import App, ComposeResult
from textual.containers import Grid
from textual.widgets import Label

class BaseApp(App):

    def compose(self) -> ComposeResult:
        with Grid(id="base-screen-container"):
            yield Label(Figlet(font="standard").renderText("reminder"))

    def on_mount(self) -> None:
        playsound("./snackaroo_jenny.mp3")


if __name__ == "__main__":
    app = BaseApp()
    app.run()
```

Here's the audio file I was using to test: [snackaroo_jenny.mp3.gz](https://github.com/Textualize/textual/files/14976988/snackaroo_jenny.mp3.gz)

Thanks for any help you can give :pray:
