### DISCUSSION TITLE
Get component styles with focus

### DISCUSSION THREAD

**Discussion by mattthhh** [Textualize/textual#4588] [Q&A]
Hello there. I do dynamic CSS in the Python code for the widget OptionList, and I get the `RenderStyles` with `get_component_classes` from DOMNode, but I want to get the same for `OptionList:focus`. Is it possible ?

If it's too hard, I just want to remove this style in default CSS of the widget :
```CSS
OptionList:focus > .option-list--option-highlighted {
    background: $accent;
}
```
Maybe this way is easier but idk how to do it...
