### DISCUSSION TITLE
OptionList layout to DialogScreen cancel the margin left&right black-line?

### DISCUSSION THREAD

**Discussion by Yurii-huang** [Textualize/textual#4840] [Q&A]
![image](https://github.com/user-attachments/assets/92908607-1226-4783-b282-3488c4933f02)

```CSS
DialogScreen {
    align: center middle;
    background: $primary 0%;
}

DiskOptions> OptionList {
    width: 50%;
    background: #bbbbbb;
    margin-left: 0;
    margin-right: 0;
}
```

How should the black vertical line pointed by the arrow in the picture be removed?
