### ISSUE TITLE
Trouble adding Input() to container using _add_child method (bug)

### ISSUE THREAD

**Issue by landowark** [Textualize/textual#1426]
Have you checked closed issues? https://github.com/Textualize/textual/issues?q=is%3Aissue+is%3Aclosed
 - As much as I could.

Please give a brief but clear explanation of the issue.
 - When trying to add in a new Input() object to a Vertical container using the instances "._add_child" method I get, after a lengthy error process the error:
```
KeyError: "No 'input--placeholder' key in COMPONENT_CLASSES"
```
This does not occur when trying to add in a different kind of widget, for example a label.

What Operating System are you running on?

- I am running on CentOS 7 with python version 3.10.6 and textual 0.7.0

If you can, include a complete working example that demonstrates the bug. Check it can run without modifications.

```python
import sys

from textual import events
from textual.app import App, ComposeResult
from textual.containers import Container, Vertical
from textual.reactive import var
from textual.widgets import DirectoryTree, Footer, Header, Input, Label

from pathlib import Path

class FormField(Input):

    def on_mount(self):
        self.placeholder = "Value not set."

    def update(self, input:str):
        self.value = input


class DataBrowser(App):
    """
    File browser input
    """    
![Keyerror](https://user-images.githubusercontent.com/14314236/209006447-c206bbb0-28af-49cd-a2c8-92c56630159e.png)

    CSS_PATH = "static/css/data_browser.css"
    BINDINGS = [
        ("f", "toggle_files", "Toggle Files"),
        ("q", "quit", "Quit"),
    ]

    show_tree = var(True)
    context = {}

    def watch_show_tree(self, show_tree: bool) -> None:
        """Called when show_tree is modified."""
        self.set_class(show_tree, "-show-tree")

    def compose(self) -> ComposeResult:
        """Compose our UI."""
        if 'directory_path' in self.context:
            path = self.context['directory_path']
        else:
            path = "."
        yield Header()
        yield Container(
            DirectoryTree(path, id="tree-view"),
            Vertical(
                Label("[b]File Name[/b]", classes='box'), FormField(id="file-name", classes='box'),
                Label("[b]Sample Type[/b]", classes='box'), FormField(id="sample-type", classes='box'),
                id="form-view"
            )
        )
        yield Footer()


    def on_mount(self, event: events.Mount) -> None:
        self.query_one(DirectoryTree).focus()


    def on_directory_tree_file_selected(self, event: DirectoryTree.FileSelected) -> None:
        """Called when the user click a file in the directory tree."""
        event.stop()
        form_view = self.query_one("#form-view", Vertical)
        form_view._add_child(Input(placeholder="Added", classes='box'))
        

    def action_toggle_files(self) -> None:
        """Called in response to key binding."""
        self.show_tree = not self.show_tree

if __name__ == "__main__":
    app = DataBrowser()
    app.run()
```

data_browser.css
```css
Screen {
    
}

.box {
    height: 3;
    border: solid green;
}

#tree-view {
    display: none; 
    scrollbar-gutter: stable;
    overflow: auto;    
    width: auto;    
    height: 100%;            
    dock: left;       
}

DataBrowser.-show-tree #tree-view {
    display: block;        
    max-width: 50%;
}

FormField {
    width: 70%;
    height: 3;
    padding: 1 2;
    background: $primary;
    border: $secondary tall;
    content-align: center middle;
}
```
