### ISSUE TITLE
Text cannot be bold via markup or CSS

### ISSUE THREAD

**Issue by ltouroumov** [Textualize/textual#2178]
The ability to **bold** text seems to be broken.

```python
with Grid(id="main"):
  yield Label(Text.from_markup("[bold]Name:[/]"), classes="label")
  yield Label("John McExample", classes="data-fw")
```

```css
#main .label {
    width: 100%;
    column-span: 1;
    text-style: bold;
    text-align: right;
}
```

Result inside of Textual
![image](https://user-images.githubusercontent.com/771888/228837193-b4933f6b-0642-4ff3-a7fd-3ae3701825c2.png)

Using Rich to print markup text
![image](https://user-images.githubusercontent.com/771888/228839119-a8c0fe24-27b1-4f66-8290-0204fcbaf12f.png)

(I use the new Windows Terminal with WSL, the same happens in PowerShell)
