### ISSUE TITLE
Feature request: support `rem` as a unit for cells

### ISSUE THREAD

**Issue by bluematt** [Textualize/textual#2496]
At the moment, Textual can use dimensionless units to represent a single character cell, e.g.

```css
MyWidget { min-width: 6; }
```

This often breaks CSS linters as CSS doesn't currently support dimensionless units (except `0`).

May I suggest that `rem` [("Font size of the root element")](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units#numbers_lengths_and_percentages) is also supported as a valid semantic unit for a character cell:

```css
/* These would be equivalent */
MyWidget { min-width: 6; }
MyWidget { min-width: 6rem; }
```

I'll look into a providing a PR even though my Python-fu is not strong.
