### ISSUE TITLE
Add opacity to Rules

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#270]
Add an "opacity" rule to the CSS and Styles object.

For instance:

```css
.header {
    opacity: 0.7;
}
```

This value should be capped between 0 and 1. It should also accept a percentage equivalent, i.e. 0% to 100%
