### ISSUE TITLE
Button and Input's height couldn't be set to 1 cell

### ISSUE THREAD

**Issue by zhongqingg** [Textualize/textual#2733]
I set the Button and Input to '1 line' height in css, but the text on the button can't show out, and the height of button seems to be 2 line, while the Input keeps 3 line height.

my python code is here:

``` python
from textual.app import App, ComposeResult
from textual.widgets import TextLog
from textual.widgets import Button, Footer, Header, Static, Input, Label

class ControlZone(Static):
    def compose(self) -> ComposeResult:
        yield Button(label="prev", id="prev", variant="success")
        yield Input("0", id="curNo")

class TextLogApp(App):
    CSS_PATH = "test.css"
    BINDINGS = [("d", "toggle_dark", "Toggle dark mode")]

    def compose(self) -> ComposeResult:
        yield Header()
        yield Footer()
        yield ControlZone()
        yield TextLog(highlight=True, markup=True, wrap=False)

if __name__ == "__main__":
    app = TextLogApp()
    app.run()
```

and the css code is here:

``` css
ControlZone {
    layout: horizontal;
    margin: 0;
    padding: 0;
}
Button {
    content-align: center middle;
    width: 5;
    height: 1;
    margin: 0;
    padding: 0;
}
Input {
    content-align: center middle;
    width: 5;
    height: 1;
    margin: 0;
    padding: 0;
}
```
the app screenshot is here:

![image](https://github.com/Textualize/textual/assets/135119022/73a070fa-7e5a-4331-8a1f-4e898fef2120)

when i change the height to 3, the app shows normal like this:

![image](https://github.com/Textualize/textual/assets/135119022/bde016db-2acb-4b93-8b6c-16d7f7e2a461)

i read the documents and refer to the #1377 , but i failed to solve my problem after trying set the `min-height: 1`
