### ISSUE TITLE
Missing link styles in `Toast` notifcations

### ISSUE THREAD

**Issue by TomJGooding** [Textualize/textual#3530]
This follows on from discussion #3526 about adding a clickable link in a notification.

 The `Toast` widget doesn't inherit the styling from the base class, so the "default" links styling defined in Widget is lost. You can obviously just add it back in like I've done here, but it might be nicer if you didn't have to do that.

```python
# toast_with_link.py

import webbrowser

from textual.app import App


class ToastLinkApp(App):
    # Uncomment the CSS_PATH to see the link!
    # CSS_PATH = "toast_with_link.css"

    def on_mount(self) -> None:
        self.notify(
            "Don't forget to "
            "[@click=link('https://github.com/Textualize/textual')]star[/] "
            "the repository!",
            timeout=10,
        )

    def action_link(self, href: str) -> None:
        webbrowser.open(href)


if __name__ == "__main__":
    app = ToastLinkApp()
    app.run()
```

```css
/* toast_with_link.css */

Toast {
  link-background: ;
  link-color: $text;
  link-style: underline;
  link-hover-background: $accent;
  link-hover-color: $text;
  link-hover-style: bold not underline;
}
```
