### ISSUE TITLE
TextArea Disappears when Using Percentage Height

### ISSUE THREAD

**Issue by elkinaguas** [Textualize/textual#3797]
Hello,

I'm using a TextArea inside a ScrollableContainer. I set its width to 100% (Percentage width) and its height to 40 (Explicit cell height) and I can see and type in the TextArea. See the image below:

![image](https://github.com/Textualize/textual/assets/18745015/8d4df6bd-166e-4d0c-98b7-2f15e57a18f6)

When I set its height to 100% (Percentage height) or any other percentage height, the TextArea disappears. See image below.

![image](https://github.com/Textualize/textual/assets/18745015/d39aec37-3044-4056-bc69-c865e85fde9f)

Result from `textual diagnose` command:

```
# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.44.0 |
| Rich    | 13.7.0 |

## Python

| Name           | Value                                                          |
|----------------|----------------------------------------------------------------|
| Version        | 3.10.12                                                        |
| Implementation | CPython                                                        |
| Compiler       | GCC 11.4.0                                                     |
| Executable     | /home/elkin/Desktop/Doing/github/Venv/forevernotes/bin/python3 |

## Operating System

| Name    | Value                                                            |
|---------|------------------------------------------------------------------|
| System  | Linux                                                            |
| Release | 6.2.0-37-generic                                                 |
| Version | #38~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov  2 18:01:13 UTC 2 |

## Terminal

| Name                 | Value          |
|----------------------|----------------|
| Terminal Application | *Unknown*      |
| TERM                 | xterm-256color |
| COLORTERM            | truecolor      |
| FORCE_COLOR          | *Not set*      |
| NO_COLOR             | *Not set*      |

## Rich Console options

| Name           | Value                |
|----------------|----------------------|
| size           | width=173, height=43 |
| legacy_windows | False                |
| min_width      | 1                    |
| max_width      | 173                  |
| is_terminal    | True                 |
| encoding       | utf-8                |
| max_height     | 43                   |
| justify        | None                 |
| overflow       | None                 |
| no_wrap        | False                |
| highlight      | None                 |
| markup         | None                 |
| height         | None                 |

```

**Comment by willmcgugan** [comment]
Can you give as a minimal reproducible example? i.e. a standalone piece of code that reproduces the problem.

**Comment by elkinaguas** [comment]
Sure, here it is:

```python
from textual.app import App, ComposeResult
from textual.containers import ScrollableContainer
from textual.widgets import Button, Footer, Header, Static, TextArea, Input


class SideBar(Static):    
    def compose(self) -> ComposeResult:
        yield Input(placeholder="Tag", id="tag_input")
        yield Button("Save", id="save_button")

class TextInput(Static):
    def compose(self) -> ComposeResult:
        yield TextArea()


class ExampleApp(App):
    CSS_PATH = "styleexample.tcss"

    def compose(self) -> ComposeResult:
        yield Header()
        yield Footer()
        yield ScrollableContainer(TextInput(), classes="box")
        yield ScrollableContainer(SideBar(), classes="box")

if __name__ == "__main__":
    app = ExampleApp()
    app.run()
```

```css
/*styleexample.tcss*/
Screen {
    layout: grid;
    grid-size: 2 1;
    grid-columns: 6fr 1fr;
}

.box {
    height: 100%;
    border: solid gray;
}
TextArea {
    layout: vertical;
    height: 20; /*Makes TextArea disappear when set to percentage*/
    width: 100%;
}

SideBar {
    layout: vertical;
    content-align: center middle;
    height: 100%;
}

Input {
    min-width: 100%;
    width: auto;
}

Button {
    min-width: 100%;
    width: auto;
}

#save_button {
    dock: bottom;
}
```
