### ISSUE TITLE
Colour not rendering correctly

### ISSUE THREAD

**Issue by ben-n93** [Textualize/textual#4450]
Hi there,

I've set the background colour of a widget to this hex code: `#18375f`

However, to my eye, the colour being rendered is different:

![image](https://github.com/Textualize/textual/assets/84557025/988fd653-2193-4103-ad1e-d570532a21e0)

Here is the Python and CSS code:

```py
from textual.app import App
from textual.widgets import Label


class ColorApp(App):
    CSS_PATH = "colour.tcss"

    def compose(self):
        yield Label("The quick brown fox jumps over the lazy dog!", id="lbl1")


if __name__ == "__main__":
    app = ColorApp()
    app.run()
```

```css
Label {
    color: auto 80%;
    content-align: center middle;
    height: 1fr;
    width: 100%;
}

#lbl1 {
    background: #18375f
}
```

Other colours I've tested are rendering correctly.

Thanks!
