### ISSUE TITLE
Footer with ANSI colors broken in v3.1.0

### ISSUE THREAD

**Issue by TomJGooding** [Textualize/textual#5870]
As mentioned in #5862, the footer descriptions are unreadable when `ansi_colors=True` in the app. Unfortunately it looks like the footer colors were broken in Textual v3.1.0.

Here's a comparison showing [the footer example from the docs](https://textual.textualize.io/widgets/footer/#example) but ran with `app = FooterApp(ansi_color=True)`:

## v3.0.0

![Image](https://github.com/user-attachments/assets/6e6e845e-bdab-4b5a-a6f0-190d9a44c27b)

## v3.1.0

![Image](https://github.com/user-attachments/assets/6b8e6a61-c8ad-4206-a1c5-8ee535959259)

Setting the theme to `textual-ansi` doesn't help:

![Image](https://github.com/user-attachments/assets/abc0e0b6-6e02-47fe-9a27-b120eff789e3)

**Comment by brent-lidstone** [comment]
Having just learned about ansi_colors=True recently, I had assumed this was always a problem. If this is a new issue then I would also really like to see it fixed

**Comment by willmcgugan** [comment]
Would either of you like to tackle this one? Ping me if you need any assistance.

**Comment by TomJGooding** [comment]
@willmcgugan I did spend a fair while looking into this, but unless I'm missing something obvious, this isn't easy to track down. I'm happy to have another crack at it, but I'm afraid I'll need a hint!

**Comment by brent-lidstone** [comment]
so I did some digging into this myself. I found a kind of related solution, I believe. Which is that in my opinion, if there is a footer in the app then it shouldn't be affected by transparency. My guess would be that most people would expect that the footer will stay opaque. So, in my own testing I have done this

Replacing at widgets/_footer.py line 144
https://github.com/Textualize/textual/blob/6e4f77bb48080aacac03c6141eeed0cf11b5e92e/src/textual/widgets/_footer.py#L144

```css
        &:ansi {
            /* background: ansi_default; */
            .footer-key--key {
                /* background: ansi_default; */
                color: ansi_magenta;
            }
            .footer-key--description {
                /* background: ansi_default; */
                color: ansi_default;
            }
            FooterKey:hover {
                text-style: underline;
                /* background: ansi_default; */
                color: ansi_default;
                .footer-key--key {
                    /* background: ansi_default; */
                }
            }
            FooterKey.-command-palette {
                /* background: ansi_default; */
                border-left: vkey ansi_black;
            }
        }
    }
```

Now I have no idea if this would be acceptable, I'm just brainstorming. From what I can tell, most of Textual does not change when ansi_color is set to True? Most widgets retain their colors, its not dropping the entire app immediately down to 16 colors or anything like that.

So what I'm wondering here is, can we possibly just prevent the Footer from changing the background as I've done above? In my own testing in Windows Terminal, this basically solves the problem. Like I said I would expect that the footer stays opaque.
