### ISSUE TITLE
align: center middle only aligns on horizontal axis

### ISSUE THREAD

**Issue by darrenburns** [Textualize/textual#592]
Application code:

```python
from textual.app import App, ComposeResult
from textual.widgets import Static

class JustABox(App):
    def compose(self) -> ComposeResult:
        yield Static("Hello, World!", id="box")

if __name__ == '__main__':
    app = JustABox(css_path="just_a_box.css", watch_css=True)
    app.run()
```

CSS:

```css
Screen {
    layout: dock;
    height: 100%;
}

#box {
    height: 50%;
    width: 50%;
    align: center middle;
    background: green;
}
```

Result:

<img width="855" alt="image" src="https://user-images.githubusercontent.com/5740731/176179049-e32f3235-8285-48d9-835d-5147cdeef6aa.png">
