### ISSUE TITLE
Horizontal and Vertical containers strange behaviour

### ISSUE THREAD

**Issue by darrenburns** [Textualize/textual#663]
When a `Vertical` container is inside a `Horizontal` container, and we query `.styles.layout` of the `Horizontal` container, it comes back as "vertical" 🤷 

Run the app below and press the `p` key to see what I mean.

```python
from __future__ import annotations

from rich.console import RenderableType
from rich.panel import Panel

from textual import events
from textual.app import App, ComposeResult
from textual.layout import Horizontal, Vertical
from textual.widget import Widget


class Box(Widget, can_focus=True):
    CSS = "#box {background: blue;}"

    def __init__(
        self, id: str | None = None, classes: str | None = None, *children: Widget
    ):
        super().__init__(*children, id=id, classes=classes)

    def render(self) -> RenderableType:
        return Panel("Box")


class JustABox(App):
    def compose(self) -> ComposeResult:
        yield Horizontal(
            Vertical(
                Box(id="box1", classes="box"),
                Box(id="box2", classes="box"),
                id="left_pane",
            ),
            id="horizontal",
        )

    def key_p(self):
        print(self.query("#horizontal").first().styles.layout)

    async def on_key(self, event: events.Key) -> None:
        await self.dispatch_key(event)


if __name__ == "__main__":
    app = JustABox(css_path="just_a_box.css", watch_css=True)
    app.run()

```

```scss
Screen {
    background: lightcoral;
}

#left_pane {
    background: red;
    width: 30;
    height: auto;
}

#middle_pane {
    background: green;
    width: 140;
}

#right_pane {
    background: blue;
    width: 30;
}

.box {
    height: 5;
    width: 15;
}

```
