### ISSUE TITLE
focus-within issue

### ISSUE THREAD

**Issue by darrenburns** [Textualize/textual#687]
We had a similar issue in the past that was resolved. When a child widget is focussed in the screen below, the parent pane should be red. This happens the first time you select a child. However, on selecting another child, the style (which should stay red) is reverted.

When I move my cursor over another widget, the styles are applied as expected.

https://user-images.githubusercontent.com/5740731/185113314-199d5e7f-44ac-4b8b-a434-18885d35aab9.mov

### `focus_keybinds.py`

```python
from textual import layout
from textual.app import App, ComposeResult
from textual.widgets import Static


class Label(Static, can_focus=True):
    pass


class FocusKeybindsApp(App):
    dark = True

    def on_load(self) -> None:
        self.bind("1", "focus('widget1')")
        self.bind("2", "focus('widget2')")
        self.bind("3", "focus('widget3')")
        self.bind("4", "focus('widget4')")
        self.bind("q", "focus('widgetq')")
        self.bind("w", "focus('widgetw')")
        self.bind("e", "focus('widgete')")
        self.bind("r", "focus('widgetr')")

    def compose(self) -> ComposeResult:
        yield Static("Use keybinds to shift focus between the widgets in the lists below", id="info")
        yield layout.Horizontal(
            layout.Vertical(
                Label("Press 1 to focus", id="widget1", classes="list-item"),
                Label("Press 2 to focus", id="widget2", classes="list-item"),
                Label("Press 3 to focus", id="widget3", classes="list-item"),
                Label("Press 4 to focus", id="widget4", classes="list-item"),
                classes="list",
                id="left_list",
            ),
            layout.Vertical(
                Label("Press Q to focus", id="widgetq", classes="list-item"),
                Label("Press W to focus", id="widgetw", classes="list-item"),
                Label("Press E to focus", id="widgete", classes="list-item"),
                Label("Press R to focus", id="widgetr", classes="list-item"),
                classes="list",
                id="right_list",
            ),
        )
        yield Static("No widget focused", id="footer")

    def on_descendant_focus(self):
        print("descendant focus")
        self.get_child("footer").update(
            f"Focused: {self.focused.id}" or "No widget focused"
        )

    async def on_key(self, event) -> None:
        await self.dispatch_key(event)

    def key_p(self):
        print(self.app.focused.parent)
        print(self.app.focused)


app = FocusKeybindsApp(css_path="focus_keybindings.scss", watch_css=True)
app.run()
```

### `focus_keybinds.scss`

```scss
*:focus {
  tint: red 20%;
}

#info {
  background: $primary;
  dock: top;
  height: 3;
  padding: 1;
}

#body {
  dock: top;
}

#left_list {
  width: 50%;
}

#right_list {
  width: 50%;
}

#footer {
  height: 1;
  background: $secondary;
  padding: 0 1;
  dock: bottom;
}

.list:focus-within {
  background: red;
  outline-top:  $accent-lighten-1;
  outline-bottom:  $accent-lighten-1;
}

.list {
  background: $surface;
  border-top: hkey $surface-darken-1;
}

.list-item {
  background: $surface;
  height: auto;
  border: $surface-darken-1 tall;
  padding: 0 1;
}

.list-item:focus {
  background: $surface-darken-1;
  outline: $accent tall;
}

```
