### ISSUE TITLE
Grid cell margin issue

### ISSUE THREAD

**Issue by darrenburns** [Textualize/textual#771]
Adding margin: 1 to the cells within this grid causes unexpected output:

<img width="752" alt="image" src="https://user-images.githubusercontent.com/5740731/190180955-3b10bd1f-60ca-4fda-9473-bc7d9a325b9d.png">

## `grid_buttons.py`

```python
from textual.app import App, ComposeResult
from textual.widgets import Button


class GridButtons(App):
    def compose(self) -> ComposeResult:
        yield Button.success("A")
        yield Button.success("B")
        yield Button.success("C")
        yield Button.success("D")
        yield Button.success("E")
        yield Button.success("F")


app = GridButtons(css_path="grid_buttons.css")
if __name__ == '__main__':
    app.run()
```

## `grid_buttons.css`

```scss
Screen {
    layout: grid;
    grid-size: 3;
    grid-rows: 1fr;
    grid-columns: 1fr;
}

Button {
    margin: 1;
}
```
